### ISSUE TITLE
Database Errors

### ISSUE THREAD

**Issue by jrcarl624** [MCBE-Utilities/BeAPI#23] opened 2022-02-12 01:31 UTC
___
**BeAPI Core Version**
2.2.0

**Create BeAPI Version**
2.1.0

**MCBE Version**
Production
___

**Describe the bug**
Simply writing to the database leaves it undefined
**To Reproduce**
```ts
import { client, schema, SchemaTypes, modal, Player as beApiPlayer, DatabaseUtil, Dimension as beApiDimension, Location as beApiLocation } from 'beapi-core'
interface playerInterface {
  bodyRotation: number,
  dimensionName: beApiDimension,
  headLocation: beApiLocation,
  id: string,
  isSneaking: boolean,
  location: beApiLocation,
  name: string,
  nameTag: string,
  selectedSlot: number,
  velocity: Vector,
  viewVector: Vector,
  tags: string[],
  scores: Record<string, any>,
  components: Record<string, any>,
  pack: Record<string, any>,
  firstJoin: number,
  lastJoin: number,
  deaths: number,
  joinCount: number,
}

const playerSchema = schema<playerInterface>({
  bodyRotation: SchemaTypes.Number,
  dimensionName: SchemaTypes.String,
  headLocation: SchemaTypes.Map,
  id: SchemaTypes.String,
  isSneaking: SchemaTypes.Boolean,
  location: SchemaTypes.Map,
  name: SchemaTypes.String,
  nameTag: SchemaTypes.String,
  selectedSlot: SchemaTypes.Number,
  velocity: SchemaTypes.Map,
  viewVector: SchemaTypes.Map,
  tags: SchemaTypes.Array,
  scores: SchemaTypes.Map,
  components: SchemaTypes.Map,
  pack: SchemaTypes.String,
  firstJoin: SchemaTypes.Number,
  lastJoin: SchemaTypes.Number,
  deaths: SchemaTypes.Number,
  joinCount: SchemaTypes.Number
})

const joinModal = modal('d', playerSchema);

var joinDocument = joinModal.findAll({})[0];
console.log(joinDocument)
console.log(JSON.stringify(joinModal.findAll({})[0]))

// error occurs here because joinDocument is undefined 
joinModal.write({
  bodyRotation: 0,
  dimensionName: 'overworld',
  headLocation: { x: 0, y: 0, z: 0 },
  id: '',
  isSneaking: false,
  location: { x: 0, y: 0, z: 0 },
  name: '',
  nameTag: '',
  selectedSlot: 0,
  velocity: { x: 0, y: 0, z: 0 },
  viewVector: { x: 0, y: 0, z: 0 },
  tags: [],
  scores: {},
  components: {},
  pack: {},
  firstJoin: 0,
  lastJoin: 0,
  deaths: 0,
  joinCount: 1
})
console.log(JSON.stringify(joinModal.findAll({})[0]))
```
**Expected behavior**
The database to work like the example one works
[database doc example ts](https://mcbe-utilities.github.io/BeAPI/docs/examples/databasing#typescript)
**Screenshots**
![image](https://user-images.githubusercontent.com/61999256/153690679-c85740bf-8e8f-4258-a0a1-8bf67e70a677.png)
The log 1 doesn't apply as it was for debug purposes.
**Additional context**
Working on the project for  [IDEA, Plugin IPC Related](https://github.com/MCBE-Utilities/BeAPI/issues/14)

**Comment by nobu-sh** [comment] 2022-02-12 07:15
This could occur for a multitude of reasons, Much of which we have fixed in our next production release.

First off to clear the air: 
1. The database does not accept sub-objects it is a WIP still. If you are using a map, you must use the map constructor. (If this worked its due to the Map constructor accepting objects I suppose, which goes against its types).
2. Sometimes changing schematic data will result in errors as you are changing data types and it does not understand how to handle the old data types yet. You can circumnavigate this by changing the modal name. (WIP)
3. Your documents contain keys that are not defined. EG: you removed a key. You can circumnavigate this by changing the modal name. (WIP)
4. You are storing too much data. Our current production does not utilize chunking yet so there are *technical* limits on how much a document can hold.

If none of these appear to be the issue then please use the command `/scoreboard players list` in-game and send the full results.

**Comment by jrcarl624** [comment] 2022-02-12 18:42
> 1. The database does not accept sub-objects it is a WIP still. If you are using a map, you must use the map constructor. (If this worked its due to the Map constructor accepting

This ended up working

```ts
joinModal.write({
  bodyRotation: 0,
  dimensionName: 'overworld',
  headLocation: new Map(Object.entries({ "x": 0, y: 0, z: 0 })),
  id: '',
  isSneaking: false,
  location: new Map(Object.entries({ x: 0, y: 0, z: 0 })),
  name: '',
  nameTag: '',
  selectedSlot: 0,
  velocity: new Map(Object.entries({ x: 0, y: 0, z: 0 })),
  viewVector: new Map(Object.entries({ x: 0, y: 0, z: 0 })),
  tags: [],
  scores: new Map(Object.entries({})),
  components: new Map(Object.entries({})),
  pack: new Map(Object.entries({})),
  firstJoin: 0,
  lastJoin: 0,
  deaths: 0,
  joinCount: 1
})
```
As to convert the object to a map
**World load 1**
But I did get a error
![image](https://user-images.githubusercontent.com/61999256/153724077-15c47120-99ff-4257-9929-0f1ca011a889.png)
The doc still comes back as undefined, I checked the scoreboard and it seemed to write some data
**World load 2** 

```ts
console.log(JSON.stringify(joinModal.findAll({})[0]))
joinModal.findAll({})[0].dimensionName = 'nether'
console.log(JSON.stringify(joinModal.findAll({})[0].dimensionName))
```
![image](https://user-images.githubusercontent.com/61999256/153724459-b10962c9-052c-4b97-ad70-33e9d8d974e6.png)
It seems to work just fine

**Comment by nobu-sh** [comment] 2022-02-12 19:20
The database is still a work in progress. Just ensure you pass the correct datatypes.

As for save being undefined, that may have been linked to the schema name not being changed and old data still existing. It appears it is not replicatable from the new example. 

In the near future, I'll ensure to add a vector3 datatype for xyz.

**Comment by jrcarl624** [comment] 2022-02-12 19:47
If needed, I can send over the code.
![image](https://user-images.githubusercontent.com/61999256/153725341-89f7fe29-428f-4b8e-a3e9-f6b71d9cda33.png)
![image](https://user-images.githubusercontent.com/61999256/153725348-168e536c-16db-4523-8766-815ac6edbe98.png)
Once i put it into the join event 

and once i rejoin the world is works fine?

**Comment by jrcarl624** [comment] 2022-02-12 19:48
![image](https://user-images.githubusercontent.com/61999256/153726154-e43f7b7c-d932-4542-a532-d7de4d786d31.png)
working after second join

**Comment by nobu-sh** [comment] 2022-02-12 19:51
Sure, send reproducible please.

**Comment by jrcarl624** [comment] 2022-02-12 19:58
```ts
import { client, schema, SchemaTypes, modal } from 'beapi-core'
console.log("§l§o§d---------------------------------------------------------------------")

interface playerInterface {
  bodyRotation: number,
  dimensionName: string,
  headLocation: Map<string, any>,
  id: string,
  isSneaking: boolean,
  location: Map<string, any>,
  name: string,
  nameTag: string,
  selectedSlot: number,
  velocity: Map<string, any>,
  viewVector: Map<string, any>,
  tags: string[],
  scores: Map<string, any>,
  components: Map<string, any>,
  pack: Map<string, any>,
  firstJoin: number,
  lastJoin: number,
  deaths: number,
  joinCount: number,
}

const playerSchema = schema<playerInterface>({
  bodyRotation: SchemaTypes.Number,
  dimensionName: SchemaTypes.String,
  headLocation: SchemaTypes.Map,
  id: SchemaTypes.String,
  isSneaking: SchemaTypes.Boolean,
  location: SchemaTypes.Map,
  name: SchemaTypes.String,
  nameTag: SchemaTypes.String,
  selectedSlot: SchemaTypes.Number,
  velocity: SchemaTypes.Map,
  viewVector: SchemaTypes.Map,
  tags: SchemaTypes.Array,
  scores: SchemaTypes.Map,
  components: SchemaTypes.Map,
  pack: SchemaTypes.String,
  firstJoin: SchemaTypes.Number,
  lastJoin: SchemaTypes.Number,
  deaths: SchemaTypes.Number,
  joinCount: SchemaTypes.Number
})

var log = 0
const debug = () => { log += 1; console.log(log) }

const otm = (object: Record<string, any>) => {
  return new Map(Object.entries(object))
}

client.on("OnJoin", (join) => {

  const joinModal = modal(join.getName(), playerSchema);
  debug()

  let joinDocument = joinModal.findAll({})[0];
  console.log(joinDocument)
  debug()

  switch (joinDocument) {
    case undefined:
      debug()

      joinModal.write({
        bodyRotation: join.getRotation(),
        dimensionName: join.getDimensionName(),
        headLocation: otm(join.getIPlayer().headLocation),
        id: join.getIPlayer().id,
        isSneaking: join.getIPlayer().isSneaking,
        location: otm(join.getIPlayer().location),
        name: join.getIPlayer().name,
        nameTag: join.getIPlayer().nameTag,
        selectedSlot: join.getIPlayer().selectedSlot,
        velocity: otm(join.getIPlayer().velocity),
        viewVector: otm(join.getIPlayer().viewVector),
        tags: join.getTags(),
        scores: otm({}),
        components: otm({}),
        pack: otm({}),
        firstJoin: Date.now(),
        lastJoin: Date.now(),
        deaths: 0,
        joinCount: 1
      })
      debug()
      joinDocument.save()

      console.log(JSON.stringify(joinDocument))

      client.world.sendMessage(join.getName() + " has joined the server for the first time");
      debug()

    default:
      joinDocument.joinCount += 1
      joinDocument.lastJoin = Date.now()
      join.setNameTag(joinDocument.nameTag)
  }
  joinDocument.save()
})
```

**Comment by jrcarl624** [comment] 2022-02-12 19:59
On first join it errors on save and the data saves to the scoreboard. Any join after it works fine and the data loads.

**Comment by nobu-sh** [comment] 2022-02-12 20:41
Its actually an error on your part.
your switches `default` statement is getting called due to no return or break on your `undefined` `case`.

This means `joinDocument` is getting referenced when being defined.

There are two ways of fixing this.

1. include a `break` at the end of `case undefined` like so
```js
switch (joinDocument) {
  case undefined:
    ...
    break;
  default:
    ...
}
```
2. re-assign `joinDocument` after writing and change `joinCount` to `0`.
```js
switch (joinDocument) {
  case undefined:
    joinDocument = joinModal.write({
      bodyRotation: join.getRotation(),
      dimensionName: join.getDimensionName(),
      headLocation: otm(join.getIPlayer().headLocation),
      id: join.getIPlayer().id,
      isSneaking: join.getIPlayer().isSneaking,
      location: otm(join.getIPlayer().location),
      name: join.getIPlayer().name,
      nameTag: join.getIPlayer().nameTag,
      selectedSlot: join.getIPlayer().selectedSlot,
      velocity: otm(join.getIPlayer().velocity),
      viewVector: otm(join.getIPlayer().viewVector),
      tags: join.getTags(),
      scores: otm({}),
      components: otm({}),
      pack: otm({}),
      firstJoin: Date.now(),
      lastJoin: Date.now(),
      deaths: 0,
      joinCount: 0
    })
  ...
}
```

**Comment by nobu-sh** [comment] 2022-02-12 20:46
For future reference a good notifier of whether its a BeAPI error or an error on your part; Look at the first call in the stack trace, if its your file and not BeAPI then nine out of ten times its not an issue with BeAPI.

![image](https://user-images.githubusercontent.com/61068742/153727807-6f67d2cf-702b-422b-a5fb-1001bc8773ba.png)

**Closed as completed** 2022-02-13 01:03 UTC
